CREATE DATABASE QLBH
GO

USE QLBH
GO


--FoodCategory
--Food
--Table
--Account
--BILL (1 HÓA ĐƠN CÓ NHIỀU MÓN (BILLINFO))
--BILLINFO


CREATE TABLE TABLEFOOD
(
	IDTABLEFOOD INT IDENTITY(1,1) PRIMARY KEY ,
	NAME NVARCHAR(100) NOT NULL DEFAULT N'BÀN CHƯA ĐẶT TÊN',
	STATUSTABLE NVARCHAR (100) NOT NULL DEFAULT N'Trống'-- Trống || Có Người
)
GO




CREATE TABLE ACCOUNT 
(
	USERNAME NVARCHAR(100) PRIMARY KEY ,
	DISPLAYNAME NVARCHAR (100) NOT NULL ,	
	PASSWORDACCOUNT NVARCHAR(100) NOT NULL DEFAULT '0' ,
	TYPE INT NOT NULL DEFAULT 0 -- 1 ADMIN , 0 STAFF
)
GO

INSERT INTO ACCOUNT VALUES (N'b1' , N'Thien','1',0)
INSERT INTO ACCOUNT VALUES (N'a1' , N'Nhien','1',1)


select * from ACCOUNT

CREATE TABLE FOODCATEGORY 
(
	IDFOODCATEGORY INT IDENTITY(1,1) PRIMARY KEY ,
	NAMECATEGORYFOOD NVARCHAR(100) NOT NULL DEFAULT N'CHƯA ĐẶT TÊN MÓN' 
)
GO


CREATE TABLE FOOD
(
	IDFOOD INT IDENTITY(1,1) PRIMARY KEY ,
	NAMEFOOD NVARCHAR(100) NOT NULL DEFAULT N'CHƯA ĐẶT TÊN MÓN' ,
	IDFOODCATEGORY INT NOT NULL FOREIGN KEY REFERENCES FOODCATEGORY(IDFOODCATEGORY) ,
	PRICE FLOAT NOT NULL  DEFAULT 0  ,
)
GO

CREATE TABLE BILL
(
	IDBILL INT IDENTITY(1,1) PRIMARY KEY ,
	DATECHECKIN DATE NOT NULL DEFAULT GETDATE() ,
	DATECHECKOUT DATE,
	IDTABLEFOOD INT NOT NULL FOREIGN KEY REFERENCES TABLEFOOD (IDTABLEFOOD) ,
	STATUS INT NOT NULL  DEFAULT 0  --1 LÀ ĐÃ THANH TOÁN , 0 LÀ CHƯA THANH TOÁN

)
GO


CREATE TABLE BILLINFO
(
	IDBILLINFO INT IDENTITY(1,1) PRIMARY KEY ,
	USERNAME NVARCHAR(100) NOT NULL,
	IDBILL INT NOT NULL FOREIGN KEY REFERENCES BILL (IDBILL) ,
	IDFOOD INT NOT NULL FOREIGN KEY REFERENCES FOOD(IDFOOD) ,
	COUNTFOOD INT NOT NULL DEFAULT 0 ,

	FOREIGN KEY (USERNAME) REFERENCES ACCOUNT(USERNAME)
)
GO



create Table Store
(
	UserName NVARCHAR(100) NOT NULL,
	Material NVARCHAR(100) NOT NULL ,
	DateIn date NOT NULL DEFAULT GETDATE(),
	Dateexpired date ,--ngày hết hạn
	priceIn float NOT NULL,
	amount int NOT NULL DEFAULT 1,
	category NVARCHAR(100) 
	
	primary key (username , material , datein),
	FOREIGN KEY (username) REFERENCES dbo.account(username)
)
GO


create table salary
(
	UserName NVARCHAR(100),
	Type INT NOT NULL,
	WORKDAY int,
	restday int,
	wagelevel float,
	bonus float,

	punish float,
	total float,
	
	primary key (username , Type),
	foreign key (username) references dbo.account(username)
)
GO


CREATE PROC USP_GETACCOUNTBYUSERNAME
@USERNAME NVARCHAR(100)
AS
BEGIN
	SELECT * FROM ACCOUNT WHERE USERNAME = @USERNAME
END
GO

EXEC USP_GETACCOUNTBYUSERNAME @USERNAME = "A1" 

SELECT * FROM ACCOUNT WHERE USERNAME = N'A1' AND PASSWORDACCOUNT = '1'

CREATE STORE

DROP TABLE STORE

CREATE TABLE STORE
(
	MaterialID NVARCHAR (100) PRIMARY KEY ,
	NameMaterial NVARCHAR(100),
	RecivedDate DATETIME ,
	SupplierPrice INT ,
	Unit NVARCHAR(100),
	Quantity INT 
)

INSERT STORE VALUES ('T1',N'THỊT HEO','2023-7-15',150000,N'KG',10) ,
INSERT STORE VALUES ('T2',N'THỊT BÒ','2023-7-15',200000,N'KG',10),
INSERT STORE VALUES ('T3',N'THỊT GÀ','2023-7-15',180000,N'KG',10)

CREATE PROC GetStoreByDate  @FROMDAY DATE,@TODAY DATE
AS
	BEGIN
		SELECT * FROM STORE S
		WHERE S.RecivedDate >= @FROMDAY AND S.RecivedDate<= @TODAY
	END
GO

EXEC GetStoreByDate '2023-7-14','2023-7-15'


CREATE PROC USP_Login
@UserName NVARCHAR (100), @PassWord NVARCHAR (100)
AS
	BEGIN
	SELECT * FROM ACCOUNT WHERE USERNAME=@UserName AND PASSWORDACCOUNT=@PassWord
	END
GO

SELECT * FROM ACCOUNT WHERE USERNAME='' AND PASSWORDACCOUNT=N'' OR 1=1--


INSERT TABLEFOOD VALUES ('BAN1' , 'TRONG')


CREATE PROC USP_MANAGETABLLE @SL INT
AS
	BEGIN
	DECLARE @COUNT INT;
	SELECT @COUNT=COUNT (*) FROM TABLEFOOD WHERE STATUSTABLE = N'CONGUOI' ; --INTO @COUNT

	IF @COUNT = 0 BEGIN DELETE FROM TABLEFOOD END
	IF @COUNT > 0 BEGIN RAISERROR('Hiện tại còn bàn có người.', 16, 1); RETURN; END
	
	DECLARE @I INT = 1
	WHILE @I <= @SL
		BEGIN
		INSERT INTO TABLEFOOD (NAME) VALUES(N'BÀN ' + CAST(@I AS nvarchar(100))) 
		SET @I = @I + 1 
		END
	END
GO

EXEC USP_GETTABLELIST

CREATE PROC USP_GETTABLELIST
AS SELECT * FROM TABLEFOOD
GO

-- NGAY 23/7
-- THÊM BẢNG LOẠI THỨC ĂN
INSERT FOODCATEGORY (NAMECATEGORYFOOD) VALUES (N'HẢI SẢN' )

INSERT FOODCATEGORY (NAMECATEGORYFOOD) VALUES (N'MÓN THỊT' )

INSERT FOODCATEGORY (NAMECATEGORYFOOD) VALUES (N'MÓN CANH' )

INSERT FOODCATEGORY (NAMECATEGORYFOOD) VALUES (N'NƯỚC GIẢI KHÁT' )

--THÊM BẢNG MÓN ĂN
INSERT FOOD (NAMEFOOD,IDFOODCATEGORY,PRICE) VALUES (N'TÔM XÀO CHUA NGỌT' , 1,50000)
INSERT FOOD (NAMEFOOD,IDFOODCATEGORY,PRICE) VALUES (N'NGHÊU HẤP XẢ' , 1,70000)
INSERT FOOD (NAMEFOOD,IDFOODCATEGORY,PRICE) VALUES (N'HEO KHO CẢI CHUA' , 2,55000)
INSERT FOOD (NAMEFOOD,IDFOODCATEGORY,PRICE) VALUES (N'CANH CHUA CÁ HÚ' , 3,35000)
INSERT FOOD (NAMEFOOD,IDFOODCATEGORY,PRICE) VALUES (N'COCACOLA' , 4,15000)
INSERT FOOD (NAMEFOOD,IDFOODCATEGORY,PRICE) VALUES (N'NƯỚC CHANH' , 4,15000)


--THÊM BILL DỰA THEO BÀN
INSERT BILL (DATECHECKIN,DATECHECKOUT,IDTABLEFOOD,STATUS) VALUES (GETDATE(),NULL,47,0)
INSERT BILL (DATECHECKIN,DATECHECKOUT,IDTABLEFOOD,STATUS) VALUES (GETDATE(),GETDATE(),48,1)


--thêm billinfo 
INSERT BILLINFO (USERNAME,IDBILL,IDFOOD,COUNTFOOD) VALUES ('A1',1,4,2)
INSERT BILLINFO (USERNAME,IDBILL,IDFOOD,COUNTFOOD) VALUES ('A1',1,5,2)

INSERT BILLINFO (USERNAME,IDBILL,IDFOOD,COUNTFOOD) VALUES ('B1',2,4,2)

SELECT * FROM BILLINFO WHERE IDBILL=1 

SELECT * FROM BILL WHERE IDTABLEFOOD =47  AND STATUS = 0



















